---
- name: get solr tar file
  get_url: url="{{ solr_download_url }}" dest="/usr/local/src/{{ solr_archive }}"
  register: solr_install

- name: unarchive solr
  unarchive: src="/usr/local/src/{{ solr_archive }}" dest=/usr/local/src/ copy=no
  when: solr_install|changed

- name: install solr
  command: /bin/mv /usr/local/src/{{ solr_package_name }} {{ solr_home }} creates={{ solr_home }}
  when: solr_install|changed

